name: Shell Commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github Actions"
      - name: multiline Script
        run: |
          echo "Version Node"
          node --version
          echo "Version NPM"
          npm -version
          echo "Version Java"
          java --version
          echo "Fin comandos"
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python